name: ancient-concurrent
baseurl: /ancient-concurrent
description: Cats-Effect Concurrency For Ancient Times
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0+2-30d9db34-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
